version: 2.1

jobs:
  get-notifications-jamf-pro-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Get notifications from Jamf Pro Server 1"
          command: bash scripts/jamf-pro-notifications-alerter.sh --url "https://server1.jamfcloud.com" --password "$JSS1_API_PASS"

  get-notifications-jamf-pro-2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Get notifications from Jamf Pro Server 2"
          command: bash scripts/jamf-pro-notifications-alerter.sh --url "https://server2.jamfcloud.com" --password "$JSS2_API_PASS"

workflows:
  jamf-pro-notifications-workflow:
    jobs:
      - get-notifications-jamf-pro-1
      - get-notifications-jamf-pro-2
