name: Jamf Pro Notifications Alerter

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '00 12 * * 1'

jobs:
  advisory-dev:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up JQ
        run: sudo apt-get install jq

      - name: Advisory Dev
        run: bash scripts/jamf-pro-notifications-alerter.sh --url "https://advisorydeva.jamfcloud.com" --username ${{ secrets.API_USER }} --password ${{ secrets.API_PASS }} --slack-webhook ${{ secrets.SLACK_WEBHOOK }}

  advisory-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up JQ
        run: sudo apt-get install jq
    
      - name: Advisory Prod
        run: bash scripts/jamf-pro-notifications-alerter.sh --url "https://advisory.jamfcloud.com" --username ${{ secrets.API_USER }} --password ${{ secrets.API_PASS }} --slack-webhook ${{ secrets.SLACK_WEBHOOK }}

  advisory-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up JQ
        run: sudo apt-get install jq
    
      - name: Advisory Test
        run: bash scripts/jamf-pro-notifications-alerter.sh --url "https://advisorytesta.jamfcloud.com" --username ${{ secrets.API_USER }} --password ${{ secrets.API_PASS }} --slack-webhook ${{ secrets.SLACK_WEBHOOK }}