name: Jamf Pro Notifications Alerter

on:
  workflow_dispatch:

jobs:
  get-notifications-jamf-pro-1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up JQ
        run: sudo apt-get install jq

      - name: Advisory Dev
        run: bash scripts/jamf-pro-notifications-alerter.sh --url "https://advisorydeva.jamfcloud.com" --username ${{ secrets.API_USER }} --password ${{ secrets.API_PASS }} --slack-webhook ${{ secrets.SLACK_WEBHOOK }}
        continue-on-error: true

      - name: Advisory Production
        run: bash scripts/jamf-pro-notifications-alerter.sh --url "https://advisory.jamfcloud.com" --username ${{ secrets.API_USER }} --password ${{ secrets.API_PASS }} --slack-webhook ${{ secrets.SLACK_WEBHOOK }}
        continue-on-error: true
    
      # - name: Advisory Test
      #   run: bash scripts/jamf-pro-notifications-alerter.sh --url "https://advisorytest.jamfcloud.com" --username ${{ secrets.API_USER }} --password ${{ secrets.API_PASS }} --slack-webhook ${{ secrets.ENGINEERING_CHANGELOG_SLACK_WEBHOOK }}
        